"""UMAP dimensionality reduction and HDBSCAN clustering for the topographic map.

Key design choices:
- UMAP runs on the FULL embedding matrix (not chunks) for global topological coherence.
- HDBSCAN runs on the 2D UMAP coordinates (not embedding space) for stable cluster shapes.
- Cluster labels are generated by Haiku (cheap classification, not synthesis).
- Homunculus weighting: high-importance articles are duplicated before UMAP so that
  heavily accessed regions expand to fill more map area.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import numpy as np

from wikiscapes.models import Article

if TYPE_CHECKING:
    from wikiscapes.llm.client import WikiClient


def compute_layout(
    ids: list[str],
    embeddings: np.ndarray,
    n_neighbors: int = 15,
    min_dist: float = 0.05,
    metric: str = "cosine",
    random_state: int = 42,
    init: str = "spectral",
) -> tuple[np.ndarray, np.ndarray]:
    """Run UMAP and return (raw_coords, normalized_coords).

    normalized_coords are linearly scaled to [0, 1] × [0, 1].
    """
    import umap  # type: ignore

    reducer = umap.UMAP(
        n_components=2,
        n_neighbors=n_neighbors,
        min_dist=min_dist,
        metric=metric,
        random_state=random_state,
        init=init,
    )
    coords_2d: np.ndarray = reducer.fit_transform(embeddings)
    coords_norm = _normalize(coords_2d)
    return coords_2d, coords_norm


def assign_clusters(
    coords_2d: np.ndarray,
    min_cluster_size: int = 5,
    min_samples: int = 3,
) -> np.ndarray:
    """Run HDBSCAN on 2D coordinates. Returns integer label array (-1 = noise)."""
    import hdbscan  # type: ignore

    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        metric="euclidean",
        cluster_selection_method="eom",
    )
    labels: np.ndarray = clusterer.fit_predict(coords_2d)
    return labels


def label_clusters(
    cluster_labels: np.ndarray,
    articles: list[Article],
    client: WikiClient,
    existing_labels: dict[int, str] | None = None,
    existing_membership: dict[int, set[str]] | None = None,
) -> dict[int, str]:
    """Generate 2–3 word cluster labels using Haiku.

    Skips clusters whose membership hasn't changed since last layout
    (uses existing_labels if provided).
    """
    # Group article titles by cluster
    cluster_titles: dict[int, list[str]] = {}
    for article, label in zip(articles, cluster_labels):
        label_int = int(label)
        if label_int == -1:
            continue
        cluster_titles.setdefault(label_int, []).append(article.frontmatter.title)

    result: dict[int, str] = {}

    for cluster_id, titles in cluster_titles.items():
        # Check if membership is unchanged
        current_set = set(a.frontmatter.id for a, l in zip(articles, cluster_labels) if int(l) == cluster_id)
        if (
            existing_labels
            and existing_membership
            and cluster_id in existing_labels
            and existing_membership.get(cluster_id) == current_set
        ):
            result[cluster_id] = existing_labels[cluster_id]
            continue

        titles_str = "\n".join(f"- {t}" for t in titles[:20])
        prompt = (
            f"These wiki articles belong to the same topic cluster:\n{titles_str}\n\n"
            "Give this cluster a clear, concise label of 2–3 words that captures "
            "the shared topic. Respond with ONLY the label, nothing else."
        )
        label_text = client.generate(prompt, tier="fast", max_tokens=20).strip()
        result[cluster_id] = label_text or f"Cluster {cluster_id}"

    result[-1] = "Unplaced"
    return result


def weight_embeddings_by_importance(
    ids: list[str],
    embeddings: np.ndarray,
    importances: dict[str, float],
    max_weight: int = 3,
) -> tuple[list[str], np.ndarray]:
    """Duplicate high-importance article rows before UMAP (Homunculus principle).

    Articles with importance > 0.7 are duplicated up to max_weight times.
    After UMAP, duplicate coordinates are averaged back to a single position.
    UMAP's density normalization causes weighted regions to expand on the map.

    Returns (expanded_ids, expanded_embeddings) — contains duplicates.
    Call deduplicate_weighted_coords() after layout to collapse them.
    """
    expanded_ids: list[str] = []
    expanded_rows: list[np.ndarray] = []

    for eid, vec in zip(ids, embeddings):
        importance = importances.get(eid, 0.0)
        copies = 1
        if importance > 0.7:
            copies = min(max_weight, 1 + int((importance - 0.7) / 0.1))
        for _ in range(copies):
            expanded_ids.append(eid)
            expanded_rows.append(vec)

    return expanded_ids, np.vstack(expanded_rows)


def deduplicate_weighted_coords(
    expanded_ids: list[str],
    expanded_coords: np.ndarray,
    original_ids: list[str],
) -> np.ndarray:
    """Average duplicate coordinates back to one position per article.

    Returns coords array aligned with original_ids.
    """
    from collections import defaultdict

    coord_groups: dict[str, list[np.ndarray]] = defaultdict(list)
    for eid, coord in zip(expanded_ids, expanded_coords):
        coord_groups[eid].append(coord)

    result = np.zeros((len(original_ids), 2), dtype=np.float32)
    for i, eid in enumerate(original_ids):
        group = coord_groups.get(eid)
        if group:
            result[i] = np.mean(group, axis=0)
    return result


def _normalize(coords: np.ndarray) -> np.ndarray:
    """Linearly scale coordinates to [0, 1] × [0, 1]."""
    mins = coords.min(axis=0)
    maxs = coords.max(axis=0)
    ranges = maxs - mins
    ranges[ranges == 0] = 1.0  # avoid division by zero on degenerate axes
    return (coords - mins) / ranges


def umap_params_dict(
    n_neighbors: int,
    min_dist: float,
    metric: str,
    random_state: int,
) -> dict[str, Any]:
    return {
        "n_neighbors": n_neighbors,
        "min_dist": min_dist,
        "metric": metric,
        "random_state": random_state,
    }
